"""Type aliases shared across the framework.

The aliases name the identifiers that flow between the ``World``, the
optimizers, the environments and the metric schemas (``ContextID``,
``OptimizerID``, ``MechanismID``, ``PolicyID``, ``SeedID``, ``EpisodeID``,
``AgentID``) and the container types exchanged with RLlib (``EnvType``,
``EnvConfigDict``, ``MultiAgentDict``). Most identifiers are plain strings;
the aliases exist so that signatures say which kind of identifier they expect.
They carry no runtime behaviour.

Examples
--------
>>> ContextID is str and OptimizerID is str
True
>>> actions: MultiAgentDict = {"fisher_0": 0.4}
>>> actions
{'fisher_0': 0.4}
"""

from typing import Any, Hashable, TypeAlias, Union

from gymnasium import Env
from ray.rllib.env.base_env import BaseEnv
from ray.rllib.env.multi_agent_env import MultiAgentEnv

ContextID: TypeAlias = str
"""
Unique identifier of one context stored in a ``World``.

A UUID4 string generated by the World when the context is registered (see
``World.append_context``); it keys the context registry and the mechanism
registry. It identifies one stored record, not a kind of record.
"""

OptimizerID: TypeAlias = str
"""
Unique identifier of an optimizer instance.

A UUID4 string drawn by ``build_optimizer`` and registered in the ``World``. It
namespaces the contexts of one optimizer and is stamped on every context the
optimizer's environment publishes. It is expected to stay stable for the
lifetime of an experiment.
"""


EnvType: TypeAlias = Union[BaseEnv, MultiAgentEnv, Env]
"""
Type of an environment accepted by the optimizer configurations: an RLlib
``BaseEnv``, an RLlib ``MultiAgentEnv`` or a gymnasium ``Env``.
"""


EnvConfigDict: TypeAlias = dict
"""
The ``env_config`` dictionary of the algorithm config, passed to the
environment constructor.
"""

AgentID = Hashable
"""Identifier of an agent, any hashable value (for example ``"fisher_0"``)."""

MultiAgentDict = dict[AgentID, Any]
"""A dict keyed by agent identifiers, for example ``{"fisher_0": value}``."""


PolicyID: TypeAlias = str
"""
Identifier of a base policy, such as the name given to an agent type.

It links an agent configuration to the policy that controls it. RLlib module
names add the candidate and seed to it: ``<policy>_m<mechanism>_s<seed>``.
"""


EpisodeID: TypeAlias = str
"""
Identifier of an environment episode.

In the metric schemas it keys the episodes of one seed. After
``tag_episode_with_env_idx`` it reads
``env=<i>|m=<mechanism>|ps=<policy_seed>|ss=<seed>|raw=<id>``, and the episode
metrics are filed under the part before ``|raw=``.
"""


MechanismID: TypeAlias = str
"""
Identifier of a mechanism.

Two kinds of string are typed with it. A mechanism configuration uses a name
(for example ``"quota"``) as the key of the mechanism's action, as in the
``MechanismContext.mechanism`` dictionary. The rollout and learner schemas use
the candidate index written as a string (for example ``"0"``) to key the
results of one candidate.
"""


SeedID: TypeAlias = str
"""
Identifier of a training seed, the seed written as a string (for example
``"101"``).

It keys the per-seed entries of the rollout and learner schemas, which
separate independent seeded policies of the same mechanism candidate.
"""
